### ISSUE TITLE
文章 Markdown 似乎不支持内嵌 Latex 语法。 

### ISSUE THREAD

**Issue by zhouhaobusy** [X1192176811/blog#100]
在编辑框内能按正常预览 Latex 样式
![2022-08-18_14-39](https://user-images.githubusercontent.com/71841464/185321758-a90a59b0-fd9f-4e60-8168-514bfaf07115.png)
但是发布之后，在文章页面，并不能正常显示。如下图
[Website Link](https://www.zhouhaobusy.com/articles/80)

![2022-08-18_14-40](https://user-images.githubusercontent.com/71841464/185320661-293016a1-957f-40ab-8ec5-8fb039f252ba.png)

**Comment by X1192176811** [comment]
markdown-it添加自定义插件可以支持，后来我加过，可能插件有些还是不支持
