### ISSUE TITLE
项目中的并发问题的建议

### ISSUE THREAD

**Issue by josek43326** [X1192176811/blog#109]
项目中涉及到查询保存、保存更新等一些操作，存在一些并发的问题。修复后可能更加完善点，涉及到redis的多步操作换成lua脚本会更好点，例如 saveArticleLike。

**Comment by yiuwacheng** [comment]
> saveArticleLike

你是说 方法里多步调用redis的地方用lua脚本 会更好吗 lua管道一次把redis操作全执行完会好点吗

**Comment by josek43326** [comment]
> 对的，主要是保证多个操作的原子性

**Comment by X1192176811** [comment]
这次更新会修改这部分内容
