### ISSUE TITLE
请教下 为什么切换调整端口号后接口文档就变成404了

### ISSUE THREAD

**Issue by suxioanan** [X1192176811/blog#55]
原端口号是8080,因为我本地有8080端口被占用了,只能使用其他端口号,但是,接口文档报404了

**Comment by X1192176811** [comment]
接口文档是本地访问，还是线上访问

**Comment by suxioanan** [comment]
>本地访问

**Comment by suxioanan** [comment]
http://127.0.0.1:8080/doc.html#/home  是能访问的,但是修改端口号后,就变成404了

**Comment by X1192176811** [comment]
这个我也不太清楚，用的knife4j生成的，你可以看看官方文档，端口号我觉得应该没影响

**Comment by suxioanan** [comment]
9090端口 不可以，其他端口没问题，具体什么情况 还没看

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月15日(周二) 下午4:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [X1192176811/blog] 请教下 为什么切换调整端口号后接口文档就变成404了 (Issue #55)




 
这个我也不太清楚，用的knife4j生成的，你可以看看官方文档，端口号我觉得应该没影响
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
