### ISSUE TITLE
角色管理修改菜单权限时，树形选择器没有级联 "选中/取消"

### ISSUE THREAD

**Issue by wtsclwq** [X1192176811/blog#57]
![image](https://user-images.githubusercontent.com/37504557/158849803-b7c3634b-e934-467a-8ffe-97beba2aceeb.png)

**Comment by X1192176811** [comment]
这个是因为如果全选了子菜单，父菜单id没有默认被关联上，所以取消了联动，需要自己手动全部勾选上
