### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by loongzcode** [X1192176811/blog#70]
希望可以增加文章描述，首页文章直接显示文章内容，感觉很乱，还有希望友链页面的名称、简介、头像可以自定义，头像显示52a36bafeb5a99d1c6a5aad4311e7e5e.jpg这种，感觉不太好

**Comment by X1192176811** [comment]
图片路径是做了md5去重判断生成的图片名，这个友链自定义是指的用户自己添加上去吗

**Comment by loongzcode** [comment]
![image](https://user-images.githubusercontent.com/55130487/166882405-ea904e1e-2058-4227-a23b-751277f2bd35.png)
就这一块

**Comment by X1192176811** [comment]
这个到后台管理界面修改网站配置就行了

**Comment by loongzcode** [comment]
头像链接是自动生成然后显示的吧

**Comment by loongzcode** [comment]
还有一个我不知道是不是就是这样设计的，发布完文章不会跳转到文章列表页面，，还是在发布文章页面，并且内容还在，我改了改，在saveOrUpdateArticle()里加了  this.$router.push('/article-list')

**Comment by X1192176811** [comment]
这个没设置跳转，到时可以改下

**Comment by loongzcode** [comment]
md语法好像有的没效果的

**Comment by X1192176811** [comment]
这个可以到markword-it的官网用扩展语法插件

**Comment by loongzcode** [comment]
这个知道，就是前端不太会，尝试改了下，不太行。哈哈哈哈哈，网上教程也少

**Comment by loongzcode** [comment]
文章页面我想加这个markdown-it-mark插件，应该怎么加

**Comment by X1192176811** [comment]
看官网例子那个，后面这些小bug会一起改
