### ISSUE TITLE
按照教程一步步部署完之后访问出现 Nginx 500 Internal Server Error

### ISSUE THREAD

**Issue by Waterkin** [X1192176811/blog#72]
如题
没有配置腾讯和微博登录插件
使用docker ps -a 查看发现后端文件似乎会自动挂掉 不能正常运行：
Exited (1) 5 minutes ago  blog-springboot-0.0.1.jar
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/41324537/167588112-e572f31b-0d5a-4863-acac-ae243b9ef047.png">

**Comment by Waterkin** [comment]
无域名，访问方式为: IP:端口

**Comment by X1192176811** [comment]
看下后端服务日志
