### ISSUE TITLE
访问ip:8080接口测试失败：无法访问此网站

### ISSUE THREAD

**Issue by Waterkin** [X1192176811/blog#74]
docker运行后端项目后，访问ip:8080接口测试失败，显示无法访问此网站。
![image](https://user-images.githubusercontent.com/41324537/170416320-1bbd2237-f045-40b3-97ff-f56d9ff911d4.png)

卡在了这一步，不知道是什么情况，请问该如何调试？

**Comment by X1192176811** [comment]
可以加群问具体情况
