### ISSUE TITLE
分类模块

### ISSUE THREAD

**Issue by Slickedback** [X1192176811/blog#78]
删除分类时会显示分类下还有文章，但是文章已经是删除了的，删除文章只是删除状态，这就导致文章分类还会统计到文章数量，导致文章分类统计也是统计删除了的文章和没删除的文章的总数，分类也删除不了。

**Comment by X1192176811** [comment]
有逻辑删除和物理删除，你去回收站删除就是真的删除了，你要删除分类就去回收站把文章删了就行

**Comment by Slickedback** [comment]
了解了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "X1192176811/blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [X1192176811/blog] 分类模块 (Issue #78)





 
有逻辑删除和物理删除，你去回收站删除就是真的删除了，你要删除分类就去回收站把文章删了就行
