### ISSUE TITLE
给博主提几个小问题

### ISSUE THREAD

**Issue by xiaowansheng** [X1192176811/blog#85]
1、写博客时添加居中在博客页面展示里没有效果。
2、Home.vue组件，有大量数据绑定的数据基于blogInfo计算属性，而该计算属性取的是store里的blogInfo，而blogInfo数据又来自app.vue创建时的axios获取。加载Home组件时，偶尔会由于网络原因，有时页面加载完成后axios请求的blogInfo数据还未返回，并且store里的blogInfo未初始化，就会导致Home页面里的数组绑定出现报错，错误之一：[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'websiteAuthor')"。
该问题只会在页面第一次加载时出现，清除缓存可重现问题。

**Comment by X1192176811** [comment]
1.这个居中的效果可以引入markdown-it的插件来实现，默认没解析这个
2.目前没啥好的解决方法，给了默认值也可能出现这个情况，一般都是正常显示，可以提点建议修改一下
